In [1]:
# import relevant libraries
import numpy as np

In [2]:
array0 = np.array([])

In [3]:
# find the shape of array0
array0.shape

(0,)

In [4]:
array1 = np.array([1, 2, 3, 4, 5])

In [5]:
# find the shape of array1
array1.shape

(5,)

In [6]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [7]:
# find the shape of array2
array2.shape

(3, 3)

In [8]:
array_zeros = np.zeros((4, 5))

In [9]:
# find the shape of array_zeros
array_zeros.shape

(4, 5)

In [10]:
array_ones = np.ones((3, 6))

In [11]:
# find the shape of array_ones
array_ones.shape

(3, 6)

In [12]:
array_r0 = np.random.randint(1, 50, 25)
array_r0

array([35,  3, 44,  1, 35, 46, 45, 21, 37, 11, 38, 35, 30, 47, 14, 13,  6,
       39,  2, 49, 29, 44, 26, 48, 37])

In [13]:
# find the shape of array_r0
array_r0.shape

(25,)

In [14]:
# reshape array_r0 
# to create a new multi-dimensional numpy array 
# containing array_r0's items with 5 rows & 5 columns

array_r0.reshape((5, 5))

array([[35,  3, 44,  1, 35],
       [46, 45, 21, 37, 11],
       [38, 35, 30, 47, 14],
       [13,  6, 39,  2, 49],
       [29, 44, 26, 48, 37]])

In [15]:
# note that array_r0 itself was not modified

array_r0

array([35,  3, 44,  1, 35, 46, 45, 21, 37, 11, 38, 35, 30, 47, 14, 13,  6,
       39,  2, 49, 29, 44, 26, 48, 37])

In [16]:
array_r1 = np.random.randint(1, 50, 20)
array_r1

array([21, 30, 31, 10, 27, 12, 17,  2, 35, 27, 17, 42,  9, 44, 22, 45, 11,
       35, 28, 41])

In [17]:
# find the shape of array_r1
array_r1.shape

(20,)

In [18]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 10 rows & 2 columns

array_r1.reshape((10, 2))

array([[21, 30],
       [31, 10],
       [27, 12],
       [17,  2],
       [35, 27],
       [17, 42],
       [ 9, 44],
       [22, 45],
       [11, 35],
       [28, 41]])

In [20]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 2 rows & 10 columns

array_r1.reshape((2, 10))

array([[21, 30, 31, 10, 27, 12, 17,  2, 35, 27],
       [17, 42,  9, 44, 22, 45, 11, 35, 28, 41]])

In [21]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 4 rows & 5 columns

array_r1.reshape((4, 5))

array([[21, 30, 31, 10, 27],
       [12, 17,  2, 35, 27],
       [17, 42,  9, 44, 22],
       [45, 11, 35, 28, 41]])

In [22]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items 
# with 5 rows & 4 columns

array_r1.reshape((5, 4))

array([[21, 30, 31, 10],
       [27, 12, 17,  2],
       [35, 27, 17, 42],
       [ 9, 44, 22, 45],
       [11, 35, 28, 41]])

In [23]:
# note that array_r1 itself was not modified
array_r1

array([21, 30, 31, 10, 27, 12, 17,  2, 35, 27, 17, 42,  9, 44, 22, 45, 11,
       35, 28, 41])

In [24]:
array_r2 = np.random.randint(1, 50, (4, 4))
array_r2

array([[18, 29, 12,  7],
       [38, 11, 22, 28],
       [33, 47,  5, 26],
       [ 4, 27, 30, 46]])

In [25]:
# find the shape of array_r2
array_r2.shape

(4, 4)

In [26]:
# reshape array_r2 
# to create a new one-dimensional numpy array containing array_r2's items 
# with length 16
array_r2.reshape(16)

array([18, 29, 12,  7, 38, 11, 22, 28, 33, 47,  5, 26,  4, 27, 30, 46])

In [27]:
# note that array_r2 itself was not modified

array_r2

array([[18, 29, 12,  7],
       [38, 11, 22, 28],
       [33, 47,  5, 26],
       [ 4, 27, 30, 46]])