In [1]:
# import relevant libraries

import numpy as np

In [2]:
# initialize array0 
# as a one-dimensional numpy array containing integers 0 to 4 including 0 and 4

array0 = np.arange(5)
array0

array([0, 1, 2, 3, 4])

In [3]:
# select the item at index 1 from array0

array0[1]

1

In [4]:
# select the items at indices 1 to 3 inclusive from array0

array0[1:4]

array([1, 2, 3])

In [5]:
# select the items at indices 0 to 3 inclusive from array0

array0[:4]

array([0, 1, 2, 3])

In [6]:
# select the items starting at index 3 until the end of array0

array0[3:]

array([3, 4])

In [7]:
# initialize array1 as a three-dimensional numpy array

array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# select the item in row 0 column 0 from array1 using double bracket notation

array1[0][0]

1

In [9]:
# select the item in row 0 column 0 from array1 using single bracket notation

array1[0, 0]

1

In [10]:
# select the item in row 1 column 2 from array1 using double bracket notation

array1[1][2]

6

In [11]:
# select the item in row 1 column 2 from array1 using single bracket notation

array1[1, 2]

6

In [12]:
# select first two items from row 0 of array1

array1[:1, :2]

array([[1, 2]])

In [13]:
# select first two items from every row until row 1 inclusive from array1

array1[:2, :2]

array([[1, 2],
       [4, 5]])

In [14]:
# select first two items from each row of array1

array1[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [15]:
# select row 0 from array1

array1[0]

array([1, 2, 3])

In [16]:
# select everything before row 2 from array1

array1[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# initialize array2 
# as a one-dimensional numpy array containing all even integers between 0 and 20 inclusive

array2 = np.arange(0, 21, 2)
array2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
# select the items from array2 that are greater than or equal to 12

array2[array2 >= 12]

array([12, 14, 16, 18, 20])

In [19]:
# select the items from array2 that are greater than 7 and less than 13

array2[(array2 > 7) & (array2 < 13)]

array([ 8, 10, 12])