In [1]:
# import relevant libraries

import numpy as np

In [2]:
# initialize arrayA as a one-dimensional numpy array
# containing the odd integers between 1 and 20 inclusive

arrayA = np.arange(1, 21, 2)
arrayA

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
# initialize arrayB as a one-dimensional numpy array 
# containing the integers 1 to 10 inclusive

arrayB = np.arange(1, 11)
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# add each element of arrayA to each corresponding element of arrayB,
# creating a new numpy array

arrayA + arrayB

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [5]:
# subtract each element of arrayB from each corresponding element from arrayA,
# creating a new numpy array

arrayA - arrayB

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# multiply each element of arrayA by each corresponding element of arrayB,
# creating a new numpy array

arrayA * arrayB

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190])

In [7]:
# divide each element of arrayA by each corresponding element of arrayB,
# creating a new numpy array

arrayA / arrayB

array([1.        , 1.5       , 1.66666667, 1.75      , 1.8       ,
       1.83333333, 1.85714286, 1.875     , 1.88888889, 1.9       ])

In [8]:
# initialize arrayC as a multi-dimensional numpy array with 2 rows and 3 columns

arrayC = np.array([[1, 2, 3], [4, 5, 6]])
arrayC

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# initialize arrayD as another multi-dimensional numpy array with 2 rows and 3 columns

arrayD = np.array([[7, 8, 9], [10, 11, 12]])
arrayD

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
# add each element of arrayC to each corresponding element of arrayD,
# creating a new numpy array

arrayC + arrayD

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
# subtract each element of arrayD from each corresponding element from arrayC,
# creating a new numpy array

arrayC - arrayD

array([[-6, -6, -6],
       [-6, -6, -6]])

In [12]:
# multiply each element of arrayC by each corresponding element of arrayD,
# creating a new numpy array

arrayC * arrayD

array([[ 7, 16, 27],
       [40, 55, 72]])

In [13]:
# divide each element of arrayC by each corresponding element of arrayD,
# creating a new numpy array

arrayC / arrayD

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])